### ISSUE TITLE
error: unknown command 'D:\solft\nodejs\node.exe'

### ISSUE THREAD

**Issue by Osub** [gemstation/gemforge#18]
$ node -v
v20.6.1

```
$ gemforge scaffold --folder ./demo  
error: unknown command 'D:\solft\nodejs\node.exe'

**Comment by hiddentao** [comment]
What OS are you running on? I haven't tried on Windows yet.

**Comment by Osub** [comment]
Windows

**Comment by hiddentao** [comment]
Ok, so I definitely haven't tried on Windows yet.

Btw, does that file exist? It's trying to find the node executable.

**Comment by hiddentao** [comment]
Going to close this for now. Have successfully tested on Windows since.
