### ISSUE TITLE
Make all methods external in IDiamondProxy interface

### ISSUE THREAD

**Issue by amarinkovic** [gemstation/gemforge#44]
In case when gemforge is configured to include public methods from the facets (`config.diamond.publicMethods`), for generating the `IDiamondProxy`, public methods are included as such. This brakes the compilation, since solidity requires all the methods in an interface to be external.

If configured to do so, gemforge should pickup the public methods, but expose them as external in the interface.

**Comment by hiddentao** [comment]
See #45

**Comment by hiddentao** [comment]
Fixed in 2.9.1
